#
# Module manifest for module 'Module'
#
# Generated by: ricardom
#
# Generated on: 8/3/2012
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\DeviceManagementCmdlet.dll'

# Version number of this module.
ModuleVersion = '0.4'

# ID used to uniquely identify this module
GUID = 'a00eb686-ca58-4c6f-aa56-a829e6312120'

# Author of this module
Author = 'ricardom'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '(c) 2012 Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell Cmdlets, written in Managed Code, that expose hardware topology information as well as PNP device discovery and control.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = '3.0'

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = '4.5'

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @('')

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module.
# ModuleList = @('')

# List of all files packaged with this module
#FileList = @('.\DeviceManagementCmdlet.dll', '.\DeviceManagementEngine.dll')

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''
}