#
# Module manifest for module 'Environment'
#
# Generated by: Christos Gkantsidis
#
# Generated on: 13/10/2015
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Environment.psm1'

# Version number of this module.
ModuleVersion = '1.1'

# ID used to uniquely identify this module
GUID = 'c5ba03d1-e96d-4659-9d05-5d06078cf692'

# Author of this module
Author = 'Christos Gkantsidis'

# Company or vendor of this module
CompanyName = 'Christos Gkantsidis'

# Copyright statement for this module
Copyright = '(c) 2015 Christos Gkantsidis. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Various functions to discover the host environment'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @(
    'Clear-FusionLogs',
    'Compare-Directories',
    'ConvertFrom-UnixDate',
    'ConvertTo-UnixDate',
    'Enable-DotNetLoadingDebugging',
    'Disable-DotNetLoadingDebugging',
    'Get-Bootup',
    'Get-ChildItemByPage',
    'Get-ChildItemWithHidden',
    'Get-ChildItemWithStreams',
    'Get-ChildItemWithOwner',
    'Get-ExecutableType',
    'Get-FileHead',
    'Get-HwInfo',
    'Get-InstalledApplications',
    'Get-ListOfLogons',
    'Get-ModuleInstall',
    'Get-MsiFileInformation',
    'Get-NotepadPlusPlusPath',
    'Get-OsInfo',
    'Get-PathFromRegistry',
    'Get-PendingReboot',
    'Get-ShimProperties',
    'Get-SystemDebugger',
    'Get-WebProxy',
    'Get-WindowsProductKey',
    'Get-WinlogonHistory',
    'Install-Scoop',
    'Reset-ForegroundColor',
    'Restart-Process',
    'Save-EnvironmentSettings',
    'Set-SystemDebugger',
    'Show-Calendar',
    'Test-HasChocolatey',
    'Test-HasEmacs',
    'Test-IsIse',
    'Test-HasNotepadPlusPlus',
    'Test-HasVisualStudio',
    'bg'
)

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = @(
    'cal',
    'color',
    'dir/a',
    'dir/p',
    'dir/q',
    'head'
)

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

